### ISSUE TITLE
'light' is not recognized as an internal or external command, operable program or batch file. 'candle' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by Haneesh000** [electron-userland/electron-wix-msi#156]
When I try to run electron-wix-msi then I get the following error

light' is not recognized as an internal or external command,
operable program or batch file.
'candle' is not recognized as an internal or external command,

```const { MSICreator } = require("electron-wix-msi");
const path = require("path");
const APP_DIR = path.resolve(__dirname, "./app-win32-x64");
const OUT_DIR = path.resolve(__dirname, "./installer");
const msiCreator = new MSICreator({
   appDirectory: APP_DIR,
    outputDirectory: OUT_DIR,
    description: "app desktop -- www.test.com",
    exe: "app",
    name: "app",
    manufacturer: "test",
    version: "1.0.0",
    ui: {
        chooseDirectory: false,
    },
    appIconPath: "C:/Users/91924/VS Code/electron/test/favicon.ico"
});
async function createMSI() {
    await msiCreator.create();
    await msiCreator.compile();
}
createMSI();
```

**Comment by bitdisaster** [comment]
You need to install the Wix Toolkit and add it to your Path variable.

**Comment by gabrielyotoo** [comment]
What if I installed WiX Toolset v3.14.1 using chocolatey, I can call `light` and `candle`, but when I try to make the app, it says it cannot find?

I had to create aliases to `light` and `candle` commands (like `Set-Alias light "C:\Program Files (x86)\WiX Toolset v3.14\bin\light.exe"`) to prevent refreshing the env (which seens impossible to do in Gitlab CI) do you think that's the problem?

This is happening in Gitlab CI btw

```txt
$ light
Windows Installer XML Toolset Linker version 3.14.1.8722
Copyright (c) .NET Foundation and contributors. All rights reserved.
 usage:  light.exe [-?] [-b bindPath] [-nologo] [-out outputFile] objectFile [objectFile ...] [@responseFile]
   ...
$ candle
Windows Installer XML Toolset Compiler version 3.14.1.8722
Copyright (c) .NET Foundation and contributors. All rights reserved.
 usage:  candle.exe [-?] [-nologo] [-out outputFile] sourceFile [sourceFile ...] [@responseFile]
  ...
$ yarn make
❯ Checking your system
❯ Checking git exists
❯ Checking node version
❯ Checking packageManager version
...
'light' is not recognized as an internal or external command,
operable program or batch file.
'candle' is not recognized as an internal or external command,
operable program or batch file.
It appears that electron-wix-msi cannot find candle.exe or light.exe.
Please consult the readme at https://github.com/felixrieseberg/electron-wix-msi
for information on how to install the Wix toolkit, which is required.
✖ Making a wix distributable for win32/x64 [FAILED: Could not find light.exe or candle.exe]
✖ Making distributables [FAILED: Could not find light.exe or candle.exe]
An unhandled rejection has occurred inside Forge:
Error: Could not find light.exe or candle.exe
at MSICreator.<anonymous> (C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\electron-wix-msi\lib\creator.js:153:23)
    at Generator.next (<anonymous>)
    at C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\electron-wix-msi\lib\creator.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\electron-wix-msi\lib\creator.js:4:12)
    at MSICreator.compile (C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\electron-wix-msi\lib\creator.js:146:16)
    at MakerWix.make (C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\@electron-forge\maker-wix\dist\MakerWix.js:44:43)
    at async C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\@electron-forge\core\dist\api\make.js:187:55
    at async _Task.taskFn (C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\@electron-forge\tracer\dist\index.js:58:20)
    at async _Task.run (C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\listr2\dist\index.cjs:2063:11)
```
