### ISSUE TITLE
Could not parse semantic version input string

### ISSUE THREAD

**Issue by footniko** [electron-userland/electron-wix-msi#159]
Unable to build assets (Github actions) :(
**OS**: Windows Server 2022
**Node**: 16.19.0
**Npm**: 8.19.3

```
electron-forge make

[STARTED] Checking your system
[STARTED] Checking git exists
[STARTED] Checking node version
[STARTED] Checking packageManager version
[TITLE] Found node@16.19.0
[SUCCESS] Found node@[16]
[TITLE] Found git@2.39.0.windows.1
[SUCCESS] Found git@2.39.0.windows.1
[TITLE] Found npm@8.[19]
[SUCCESS] Found npm@8.19.3
[SUCCESS] Checking your system
[STARTED] Loading configuration
[SUCCESS] Loading configuration
[STARTED] Resolving make targets
[DATA] Making for the following targets: wix
[SUCCESS] Resolving make targets
[STARTED] Running package command
[STARTED] Preparing to package application
[SUCCESS] Preparing to package application
[STARTED] Running packaging hooks
[STARTED] Running generateAssets hook
[SUCCESS] Running generateAssets hook
[STARTED] Running prePackage hook
[STARTED] [plugin-webpack] Preparing native dependencies
[TITLE] [plugin-webpack] Preparing native dependencies
[SUCCESS] [plugin-webpack] Preparing native dependencies
[STARTED] [plugin-webpack] Building webpack bundles
[SUCCESS] [plugin-webpack] Building webpack bundles
[SUCCESS] Running prePackage hook
[SUCCESS] Running packaging hooks
[STARTED] Packaging application
[DATA] Determining targets...
[STARTED] Packaging for x64 on win[32]
[STARTED] Copying files
[SUCCESS] Copying files
[STARTED] Preparing native dependencies
[TITLE] Preparing native dependencies
[SUCCESS] Preparing native dependencies
[STARTED] Finalizing package
[SUCCESS] Finalizing package
[SUCCESS] Packaging for x64 on win32
[SUCCESS] Packaging application
[STARTED] Running postPackage hook
[SUCCESS] Running postPackage hook
[SUCCESS] Running package command
[STARTED] Running preMake hook
[SUCCESS] Running preMake hook
[STARTED] Making distributables
[STARTED] Making a wix distributable for win32/x64
[FAILED] Could not parse semantic version input string
[FAILED] Could not parse semantic version input string

An unhandled rejection has occurred inside Forge:
Error: Could not parse semantic version input string
at getWindowsCompliantVersion (D:\a\app\node_modules\electron-wix-msi\lib\utils\version-util.js:28:15)
    at new MSICreator (D:\a\app\node_modules\electron-wix-msi\lib\creator.js:78:86)
    at MakerWix.make (D:\a\app\node_modules\@electron-forge\maker-wix\dist\MakerWix.js:30:25)
    at async Task.task (D:\a\app\node_modules\@electron-forge\core\dist\api\make.js:197:55)
    at async Task.run (D:\a\app\node_modules\listr2\dist\index.cjs:978:11)
    at async D:\a\app\node_modules\p-map\index.js:[57]
Error: Process completed with exit code 1.
```

**Comment by footniko** [comment]
The root cause was an invalid package.json version.
